###### CODIFICACION DE CATEORIAS

In [1]:
import pandas as pd
import numpy as np

In [35]:
dataset = pd.DataFrame([
    ("Mexico","Married", "High school"),
    ("Colombia","Single","Undergraduate"),
    ("Guinea Equatorial","Divorced","College"),
    ("Mexico","Single","Primary"),
    ("Colombia","Single","Primary"), 
    ], columns = ["Country","Marital Status","Education"
    
])

dataset

Country Marital Status      Education
0             Mexico        Married    High school
1           Colombia         Single  Undergraduate
2  Guinea Equatorial       Divorced        College
3             Mexico         Single        Primary
4           Colombia         Single        Primary

In [36]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
encoder = OneHotEncoder()

In [38]:
encoder.fit(dataset[['Country']])

OneHotEncoder()

In [39]:
country_encoded = encoder.transform(dataset[['Country']])
country_encoded.todense()

matrix([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

In [40]:
encoder.transform(dataset[['Country']])

<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [42]:
encoder.categories_

[array(['Colombia', 'Guinea Equatorial', 'Mexico'], dtype=object)]

In [43]:
encoder.inverse_transform(country_encoded)

array([['Mexico'],
       ['Colombia'],
       ['Guinea Equatorial'],
       ['Mexico'],
       ['Colombia']], dtype=object)

In [44]:
error_encoder = OneHotEncoder(handle_unknown = 'error', sparse_output = False)
ignore_encoder = OneHotEncoder(handle_unknown = 'ignore', sparse_output = False)

In [45]:
error_encoder.fit(dataset[['Country']])
ignore_encoder.fit(dataset[['Country']])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [46]:
new_data = pd.DataFrame(['Costa Rica'], columns = ['Country'])
new_data

Country
0  Costa Rica

In [47]:
error_encoder.transform(new_data)

ValueError: Found unknown categories ['Costa Rica'] in column 0 during transform

In [48]:
ignore_encoder.transform(new_data)

array([[0., 0., 0.]])

##### Ordinal Encoding

In [49]:
from sklearn.preprocessing import OrdinalEncoder

In [52]:
ordinal_encoder = OrdinalEncoder(categories=[[
    "Primary", "Secondary", "High school", "Undergraduate", "College"
    
]])

In [53]:
ordinal_encoder.fit(dataset[['Education']])

OrdinalEncoder(categories=[['Primary', 'Secondary', 'High school',
                            'Undergraduate', 'College']])

In [54]:
ordinal_encoder.transform(dataset[['Education']])

array([[2.],
       [3.],
       [4.],
       [0.],
       [0.]])

In [55]:
dataset[['Education']]

Education
0    High school
1  Undergraduate
2        College
3        Primary
4        Primary

In [63]:
error_encoder = OrdinalEncoder(categories=[[
    "Primary", "Secondary", "High school", "Undergraduate", "College"
]], handle_unknown = 'error')

In [64]:
error_encoder.fit(dataset[['Education']])

OrdinalEncoder(categories=[['Primary', 'Secondary', 'High school',
                            'Undergraduate', 'College']])

In [69]:
default_encoder = OrdinalEncoder(categories=[[
    "Primary", "Secondary", "High school", "Undergraduate", "College"
]], handle_unknown = 'use_encoded_value', unknown_value=np.nan)

default_encoder.fit(dataset[['Education']])

OrdinalEncoder(categories=[['Primary', 'Secondary', 'High school',
                            'Undergraduate', 'College']],
               handle_unknown='use_encoded_value', unknown_value=nan)

In [ ]:
default_encoder.transform([["Kindergrarten"]])